typedef enum {
    CK_POWER= 0,
    CK_MAIN_MENU,
    CK_BACK,
    CK_OPTION,
    CK_MENU,
    CK_DELETE,
    CK_SETUP,
    CK_VOL_INC,
    CK_VOL_DEC,
    CK_MUTE,
    CK_CLK,
    CK_DISP,
    CK_FMAM = 0x20,
    CK_FM,
    CK_AM,
    CK_MEDIA,
    CK_USB,
    CK_SD,
    CK_HDD,
    CK_DISC,
    CK_IPOD,
    CK_TV,
    CK_AUX,
    CK_MODE,
    CK_CAMERA,
    CK_SOS,
    CK_NAVI,
    CK_NAVI_ONEKEY,
    CK_MAP,
    CK_DEST,
    CK_VR,
    CK_GAME,
    CK_AVM,
    CK_BLD,
    CK_TEL,
    CK_HANDUP,
    CK_INFO,
    CK_IE,
    CK_AUDIO,
    CK_EJECT,
    CK_SEL_LEFT = 0x40,
    CK_SEL_RIGHT,
    CK_UP,
    CK_DOWN,
    CK_LEFT,
    CK_RIGHT,
    CK_OK,
    CK_NUM0,
    CK_NUM1,
    CK_NUM2,
    CK_NUM3,
    CK_NUM4,
    CK_NUM5,
    CK_NUM6,
    CK_NUM7,
    CK_NUM8,
    CK_NUM9,
    CK_STAR,
    CK_JING,
    CK_RPT = 0x70,
    CK_RDM,
    CK_SCAN,
    CK_PRE,
    CK_NEXT,
    CK_SEEK_UP,
    CK_SEEK_DOWN,
    CK_FOLD_UP,
    CK_FOLD_DOWN,
    CK_FF,
    CK_FB,
    CK_AS,
    CK_PLAY,
    CK_PAUSE,
    CK_STOP,
    CK_PLAYPAUSE,

    CK_NONE = 0xff,
    
}CK_CODE;


