

typedef enum tuner_to_hmi_msg_enum
{
    OP_TUNER_UPD_NULL = 0,
    OP_TUNER_UPD_CURRENTLY,        //Currently Information Packet Sync...    
    OP_TUNER_UPD_CURRENT_BAND,    //Currently Band Sync
    OP_TUNER_UPD_CURRENT_FREQ,    
    OP_TUNER_UPD_CURRENT_PRESET,
    OP_TUNER_UPD_PRESET_LIST,    //Newly Preset List Update
    OP_TUNER_UPD_ONE_PRESET,    //Update One new Preset :+ Band + Preset
    OP_TUNER_UPD_SIGNAL_STR,    
    OP_TUNER_UPD_SEEK_STATE,
    OP_TUNER_UPD_SETTING,
    OP_TUNER_UPD_STATUS,        //Currently Status
    OP_TUNER_UPD_VALID_LIST,
    OP_TUNER_UPD_VALID_HIGHLIGHT,
    OP_RDS_UPD_STATUS,
    OP_RDS_UPD_PS_NAME,
    OP_RDS_UPD_PS_LIST,
    OP_RDS_UPD_ONE_PS,  //Update One Preset PS Name : + Band + Preset Number
    OP_RDS_UPD_CURRENT_PTY,
    OP_RDS_UPD_SELECTED_PTY,    //Sync Selected PTY ...
    OP_RDS_UPD_RT,
    OP_TUNER_UPD_AREA,
}TUNER_TO_HMI_MSG_ENUM;

typedef enum tuner_output_msg_change_enum
{
    OP_TUNER_CHANGE_NULL = 0,
    OP_TUNER_CHANGE_BAND,
    OP_TUNER_CHANGE_PRESET,
    OP_TUNER_CHANGE_SIGNALSTR,
    OP_TUNER_CHANGE_STATE,
    OP_TUNER_CHANGE_FREQ,
    OP_TUNER_CHANGE_SETTING,
    OP_TUNER_CHANGE_PTY,
    OP_TUNER_CHANGE_PERIODICOUT,
    OP_TUNER_CHANGE_SYNCDATA,
}TUNER_OUTPUT_MSG_CHANGE_ENUM;

//Tuner Received Msg...
typedef enum tuner_input_operate_enum
{
    OP_TUNER_SET_NULL = 0,
    OP_TUNER_SET_SYNC,
    OP_TUNER_SET_BAND,
    OP_TUNER_SET_BAND_INC,
    OP_TUNER_SET_BAND_DEC,
    OP_TUNER_SET_BAND_FM,
    OP_TUNER_SET_BAND_AM,
    OP_TUNER_SET_BAND_OIRT,
    OP_TUNER_SET_BAND_SEL,    //Band Select: + Band ID
    OP_TUNER_SET_STEP_INC,
    OP_TUNER_SET_STEP_DEC,
    OP_TUNER_SET_PRESET_INC,
    OP_TUNER_SET_PRESET_DEC,
    OP_TUNER_SET_SEEK_INC,
    OP_TUNER_SET_SEEK_DEC,
    OP_TUNER_SET_AMS,
    OP_TUNER_SET_SCAN,
    OP_TUNER_SET_PRESET_SCAN,
    OP_TUNER_SET_PRESET1,
    OP_TUNER_SET_PRESET2,
    OP_TUNER_SET_PRESET3,
    OP_TUNER_SET_PRESET4,
    OP_TUNER_SET_PRESET5,
    OP_TUNER_SET_PRESET6,
    OP_TUNER_SET_SAVE1,
    OP_TUNER_SET_SAVE2,
    OP_TUNER_SET_SAVE3,
    OP_TUNER_SET_SAVE4,
    OP_TUNER_SET_SAVE5,
    OP_TUNER_SET_SAVE6,
    OP_TUNER_SET_LOC_DX,
    OP_TUNER_SET_LOC,
    OP_TUNER_SET_DX,
    OP_TUNER_SET_STEREO,
    OP_TUNER_SET_TA,
    OP_TUNER_SET_AF,
    OP_TUNER_SET_PTY,        //PTY Setting
    OP_TUNER_SET_PTY_INC,
    OP_TUNER_SET_PTY_DEC,
    OP_TUNER_SET_PTY_SEL,        //4:+Selected Pty Type
    OP_TUNER_SET_REG,
    OP_TUNER_SET_EON,
    OP_TUNER_SET_CT,
    OP_TUNER_SET_DIRECT_TUNE,    //4Directly tune to a frequency:+Freq_h+Freq_L
    OP_TUNER_SET_SECT_SEEK,        //4 Section Seek:+ New Freq_H + New Freq_L
    OP_TUNER_SET_BREAK,
    OP_TUNER_SET_PTY_SEEK,
    OP_TUNER_SET_ANT,//Set Antenna Gain : 0~X 
    OP_TUNER_SET_PAUSE,//Set PAUSE
    OP_TUNER_STOP_SEEK,
    OP_TUNER_SET_NUM
}TUNER_INPUT_OPERATE_ENUM;

